name: dicomviewer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.14
  - numpy
  - pydicom
  - pyqt
  - pip
  - pip:
      - pylibjpeg
      - pylibjpeg-libjpeg
      - pylibjpeg-openjpeg
